version: "3.3"

services:
  app:
    container_name: ${APP_NAME}
#    image: ${APP_NAME}:${APP_CONTAINER_VERSION}
    build:
      context: .
      dockerfile: services/app/Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./app:/usr/asilum
#    - ./resources:/app/resources
#    - ./logs:/logs
    tty: true